[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg"]
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

# API function proxies
[[redirects]]
  from = "/api/inspections/insert"
  to = "/.netlify/functions/inspections-insert"
  status = 200

# Simple admin API route
[[redirects]]
  from = "/api/simple-admin-data"
  to = "/.netlify/functions/simple-admin-data"
  status = 200

# Admin API routes
[[redirects]]
  from = "/api/admin/login"
  to = "/.netlify/functions/admin-login"
  status = 200

[[redirects]]
  from = "/api/admin/logout"
  to = "/.netlify/functions/admin-logout"
  status = 200

[[redirects]]
  from = "/api/admin/data"
  to = "/.netlify/functions/admin-data"
  status = 200

[[redirects]]
  from = "/api/admin/db-ping"
  to = "/.netlify/functions/admin-db-ping"
  status = 200

[[redirects]]
  from = "/api/admin/tables"
  to = "/.netlify/functions/admin-tables"
  status = 200

[[redirects]]
  from = "/api/admin/sample"
  to = "/.netlify/functions/admin-sample"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200